- devops/go.mod
- devops/go.sum
- devops/internal/service/callback.go
> feat: [devops]degrade cloudwego/eino to v0.3.0

- devops/model/canvas.go
en:
zh(optional): 
Referencing issue #11 for more details.
>  feat(devops): add Extra in GraphSchema to store additional information such as code locations

- libs/acl/openai/embedding.go
chore: openai embedding acl config customization
en: 
openai acl: alignment of embedding client and chat client initialization
1. azure openai: azure version 
2. openai: base url
zh: 
对齐 openai embedding client 和 chat client 初始化：
1. azure openai 协议：支持设置 azure version
2. openai 协议：支持设置 base url
> chore: openai embedding config customization

- components/embedding/ark/embedding.go
- components/model/ark/chatmodel.go
- libs/acl/openai/chat_model.go
optimize: replace ManagerFromCtx
en: replace ManagerFromCtx due to upgrade of eino callbacks，no impact on users
zh(optional): 替换组件切面方法，兼容 eino callback 升级，对用户无影响
> optimize: replace ManagerFromCtx

- devops/model/canvas.go
> feat(devops): add config schema definition and delete imply type definition

- devops/model/canvas.go
Change-Id: I9f7727a2b0bdc61c769f1aa7550d6210ab244656
en:
zh(optional):
> feat(devops): component schema add slots

- devops/model/canvas.go
Change-Id: I9ee55aeacdb8b6ad45ce1b22b831268ab266980c
en:
zh(optional):
> feat(devops): modify slot add config field name

- devops/internal/model/container.go
> feat(devops): add ImplType of ComponentSchema

- devops/model/canvas.go
Change-Id: Id9ab4fce7716d757881886b3cb0e5048e58efff9
en:
zh(optional):
> chore(devops): use  config field loc path in slot struct

- devops/internal/model/container.go
- devops/internal/model/container_test.go
- devops/internal/service/callback.go
- devops/model/canvas.go
> chore(devops): JsonSchema add Go Definition

- devops/model/canvas.go
> feat: add ToolsNode Component &  Slot add GoDefinition

- devops/internal/model/container.go
- devops/model/canvas.go
> feat(devops): delete component definition

- devops/model/canvas.go
> feat(devops): add IsTitleReadOnly of JsonSchema

- devops/internal/model/container.go
- devops/model/canvas.go
> feat(devops): ComponentSchema add name field for display

- devops/model/canvas.go
> feat(devops): use JsonSchema in GraphSchema and GenLocalState

- devops/model/canvas.go
> feat(devops): use JsonSchema in Condition

- devops/internal/apihandler/server.go
> fix(devops): modify routes url path

- devops/internal/apihandler/server.go
> feat(devops): adjust routes url path

- devops/model/canvas.go
> feat(devops): add Version in ComponentSchema

- devops/internal/mock/container_mock.go
- devops/internal/model/container.go
- devops/internal/model/container_test.go
- devops/internal/model/runnable_test.go
- devops/internal/service/callback_test.go
- devops/internal/service/container.go
- devops/internal/service/container_test.go
- devops/internal/service/debug_run.go
- devops/internal/service/debug_run_test.go
> feat(devops): adapt to eino upgrade

- components/embedding/ark/embedding.go
- components/embedding/ark/embedding_test.go
- components/embedding/openai/embedding.go
- components/embedding/openai/go.mod
- components/embedding/openai/go.sum
- components/model/ark/chatmodel.go
- components/model/ark/examples/generate_with_image/generate_with_image.go
- components/model/openai/chatmodel.go
- components/model/openai/chatmodel_test.go
- components/model/openai/examples/stream/stream.go
- components/model/openai/go.mod
- components/model/openai/go.sum
- components/model/qwen/chatmodel.go
- components/model/qwen/go.mod
- components/model/qwen/go.sum
- libs/acl/openai/chat_model.go
- libs/acl/openai/embedding.go
> fix: modiy chat model

- components/embedding/openai/go.mod
- components/embedding/openai/go.sum
- components/model/openai/go.mod
- components/model/openai/go.sum
- components/model/qwen/go.mod
- components/model/qwen/go.sum
> fix: update openi version

- components/embedding/openai/embedding.go
> fix: remove http client of openai embedding

- components/tool/googlesearch/google_search.go
- components/tool/googlesearch/google_search_test.go
Change-Id: I10862623a52834d73e40d815ba6fe6b0755f4b19
en:
zh(optional):
> fix: googlesearch: format & rename

- devops/go.mod
- devops/internal/model/container.go
> fix(devops): component schema name return imply_type

- README.md
- README.zh_CN.md
Change-Id: I3ed8ed7d38f575c070cb9aa5a15bd59c9f42ee98
en:
zh(optional):
> update readme zh table

- devops/model/canvas.go
Change-Id: I91f568e0cc373f8a2c96372644e6a307a300ced5
en:
zh(optional):
> chore(devops): devops version use 1.0.0

- devops/model/canvas.go
> feat(devops): use isSet indicates whether to set GenLocalState

- devops/internal/model/container.go
- devops/internal/model/container_test.go
- devops/internal/model/types.go
- devops/option.go
> feat(devops): processing pointer type

- components/model/ark/chatmodel.go
- components/model/claude/go.mod
- components/model/qianfan/chatmodel.go
- libs/acl/openai/chat_model.go
> feat: remove callback input tool choice

- components/model/openai/go.mod
- components/model/openai/go.sum
- components/model/qwen/go.mod
- components/model/qwen/go.sum
> feat: upgrade acl/openai of openai & qwen chat model component

- README.md
- README.zh_CN.md
- devops/README.md
- devops/README.zh_CN.md
Change-Id: I840afc20910b0312bcff01f7ddaec8cd7ede1e56
en:
zh(optional):
> chore(devops): add readme description

- components/model/deepseek/README.md
> fix: update DeepSeek README.md

- components/model/ark/chatmodel.go
- components/model/ark/chatmodel_test.go
- components/model/claude/claude.go
- components/model/claude/claude_test.go
- components/model/deepseek/deepseek.go
- components/model/deepseek/deepseek_test.go
- components/model/gemini/gemini.go
- components/model/gemini/gemini_test.go
- components/model/ollama/chatmodel.go
- components/model/ollama/chatmodel_test.go
- components/model/qianfan/chatmodel.go
- components/model/qianfan/chatmodel_test.go
- devops/internal/utils/generic/type_utils.go
- libs/acl/openai/chat_model.go
- libs/acl/openai/chat_model_test.go
> feat: remove eino utils

- .github/workflows/tests.yml
- callbacks/langfuse/langfuse.go
- devops/dev.go
> ci: add tag reminder

- callbacks/apmplus/go.mod
- callbacks/apmplus/go.sum
> feat: update apmplus go mod

- callbacks/apmplus/README.md
- callbacks/apmplus/README_zh.md
- callbacks/apmplus/examples/main.go
> docs: update apmplus doc

- devops/internal/model/types.go
> feat: not process if the key of the input map is an empty string

- devops/go.mod
- devops/go.sum
> feat(devops): upgrade eino to v0.3.14

- components/document/transformer/splitter/semantic/semantic.go
> fix: semantic config

- components/model/openai/go.mod
- components/model/openai/go.sum
- components/model/qwen/go.mod
- components/model/qwen/go.sum
升级 chat model 依赖的 libs/acl/openai
en: upgrade for bugfix, ref https://github.com/cloudwego/eino-ext/pull/137
zh(optional):
> feat: upgrade acl/openai

- components/prompt/mcp/examples/mcp.go
- components/prompt/mcp/go.mod
- components/prompt/mcp/go.sum
- components/prompt/mcp/mcp.go
- components/prompt/mcp/mcp_test.go
- components/tool/mcp/go.mod
- components/tool/mcp/go.sum
- components/tool/mcp/mcp_test.go
> feat: upgrade mcp prompt

- .github/workflows/tests.yml
- components/model/ark/chatmodel_test.go
- components/model/ark/go.mod
- components/model/ark/go.sum
> fix: ark unit test

- devops/internal/apihandler/common.go
- devops/internal/apihandler/server.go
- devops/internal/apihandler/types/common.go
feat(devops): add version api return devops current version
Change-Id: Ic5920e005042cdae1f4c94628a0bda6c0594cc06
> feat(devops): add version api return devops current version

- components/tool/duckduckgo/examples/main.go
fix: change timeout setting for ddg search example
> fix: change timeout setting for ddg search example

- components/model/claude/claude.go
修复 claude api 中 content 为空时 tools 被丢弃的问题
en:
zh(optional):
> fix: claude unexpected trunc tool calls when content is empty

- components/model/ark/chatmodel.go
fix: ark model now supports temperature set to 0
> fix: ark model now supports temperature set to 0

- components/model/claude/claude.go
fix
修复 claude callback enable 状态问题
en:
zh(optional):
> fix: claude callback enable status

- components/tool/httprequest/delete/delete.go
- components/tool/httprequest/delete/delete_test.go
- components/tool/httprequest/get/get.go
- components/tool/httprequest/get/get_test.go
- components/tool/httprequest/post/post.go
- components/tool/httprequest/post/post_test.go
- components/tool/httprequest/put/put.go
- components/tool/httprequest/put/put_test.go
> fix: simplify http request tool response

- components/prompt/mcp/examples/mcp.go
- components/prompt/mcp/go.mod
- components/prompt/mcp/go.sum
- components/tool/mcp/examples/mcp.go
- components/tool/mcp/go.mod
- components/tool/mcp/go.sum
> feat: upgrade mcp-go

- components/model/deepseek/deepseek.go
> feat: optimize deepseek baseurl

- components/indexer/volc_vikingdb/utils.go
- components/indexer/volc_vikingdb/utils_test.go
- components/retriever/volc_vikingdb/utils.go
- components/retriever/volc_vikingdb/utils_test.go
fix
修复 vikingdb 内置向量化获取到的向量类型断言失败问题
en:
zh(optional):
> fix: viking builtin-embedding type assertion

- components/tool/googlesearch/examples/main.go
feat: add google search examples
> feat: add google search examples

- components/tool/mcp/README.md
`docs`
`docs: 更新 README 以适配 mcp-go 升级`
**en:**
This PR updates the README file to reflect recent changes due to the `mcp-go` dependency upgrade. The previous documentation was outdated and might lead to confusion.
**zh:**
此 PR 更新了 README 文件，以适配 `mcp-go` 依赖的升级。之前的文档已经过时，可能会导致使用上的困惑。
> docs: update README due to mcp-go upgrade

- devops/internal/apihandler/types/common.go
fix(devops): modify devops version to 0.1.6
> fix(devops): modify devops version to 0.1.6

- callbacks/apmplus/README.md
- callbacks/apmplus/README_zh.md
- callbacks/apmplus/apmplus_test.go
- callbacks/apmplus/examples/main.go
> refactor: use AppendGlobalHandlers for apmplus

- components/indexer/volc_vikingdb/go.mod
- components/indexer/volc_vikingdb/go.sum
- components/indexer/volc_vikingdb/indexer.go
- components/prompt/mcp/go.mod
- components/prompt/mcp/go.sum
- components/retriever/volc_vikingdb/go.mod
- components/retriever/volc_vikingdb/go.sum
- components/retriever/volc_vikingdb/retriever.go
- components/tool/mcp/go.mod
- components/tool/mcp/go.sum
> feat: upgrade viking with multi modal

- components/tool/wikipedia/go.mod
- components/tool/wikipedia/go.sum
- components/tool/wikipedia/wikipedia_test.go
- devops/go.mod
- devops/go.sum
- devops/internal/apihandler/types/common.go
- devops/internal/model/container.go
> feat(devops): adapt eino NewGraphOptions

- components/model/ark/go.mod
- components/model/ark/go.sum
- components/model/ark/message_extra.go
- components/model/deepseek/extra.go
- components/model/deepseek/go.mod
- components/model/deepseek/go.sum
> feat: register custom type

- components/embedding/dashscope/embedding_test.go
- components/embedding/dashscope/go.mod
- components/embedding/dashscope/go.sum
- components/embedding/openai/embedding_test.go
- components/embedding/openai/go.mod
- components/embedding/openai/go.sum
- components/model/openai/chatmodel_test.go
- components/model/openai/examples/stream/stream.go
- components/model/openai/go.mod
- components/model/openai/go.sum
- libs/acl/openai/chat_model.go
- libs/acl/openai/chat_model_test.go
- libs/acl/openai/embedding.go
- libs/acl/openai/embedding_test.go
- libs/acl/openai/go.mod
- libs/acl/openai/go.sum
> feat: use fork openai

- components/model/claude/claude.go
> feat: claude support custom HTTPClient

- libs/acl/openai/chat_model.go
- libs/acl/openai/chat_model_test.go
- libs/acl/openai/go.mod
- libs/acl/openai/go.sum
> feat: add openai multi content

- components/model/openai/go.mod
- components/model/openai/go.sum
- components/model/qwen/examples/generate/generate.go
- components/model/qwen/go.mod
- components/model/qwen/go.sum
> feat: upgrade openai

- components/model/deepseek/README.md
- components/model/deepseek/deepseek.go
- components/model/deepseek/deepseek_test.go
- components/model/deepseek/examples/deepseek.go
- components/model/deepseek/go.mod
- components/model/deepseek/go.sum
> feat: deepseek support tool call

- components/model/openai/go.mod
- components/model/openai/go.sum
- components/model/qwen/go.mod
- components/model/qwen/go.sum
> fix: report error if bind empty tools

- libs/acl/langfuse/consumer.go
> fix: langfuse media upload

- callbacks/cozeloop/data_parser.go
update cozeloop latency_first_resp, milliseconds to microseconds
> fix cozeloop latency_first_resp

- components/model/deepseek/deepseek.go
> fix: 使用deepseek model进行function call，由于消息未填充对应的tool call id以及toocalls导致发送给deepseek服务端返回422报错

- components/model/ark/chatmodel.go
- components/model/ark/chatmodel_test.go
- components/model/deepseek/deepseek.go
- components/model/deepseek/deepseek_test.go
- libs/acl/openai/chat_model.go
- libs/acl/openai/chat_model_test.go
> feat: add logprobs

- components/tool/browseruse/browseruse.go
- components/tool/browseruse/go.mod
- components/tool/browseruse/go.sum
> fix: upgrade eino version of browseruse

- components/model/ark/chatmodel.go
- components/model/ark/go.mod
- components/model/ark/go.sum
> feat: add response format to ark

- components/model/ollama/chatmodel.go
> fix: required nil pointer if argument is empty

- components/tool/mcp/mcp.go
> feat: optimize mcp tool error

- components/indexer/milvus/README.md
- components/indexer/milvus/README_zh.md
- components/indexer/milvus/consts.go
- components/indexer/milvus/indexer.go
- components/indexer/milvus/indexer_test.go
- components/indexer/milvus/options.go
- components/retriever/milvus/README.md
- components/retriever/milvus/README_zh.md
- components/retriever/milvus/retriever.go
feat: add partition option to indexer implementation
添加索引时分区选项
en: Partition Support in Milvus Indexer
zh(optional):
> feat(components): add partition option to indexer implementation

- components/model/ark/chatmodel.go
- components/model/ark/go.mod
- components/model/ark/go.sum
> feat: ark model support thinking field

- libs/acl/openai/chat_model.go
- libs/acl/openai/go.mod
- libs/acl/openai/go.sum
- libs/acl/openai/option.go
feat: A new feature
en:
Support `ExtraFields` for openai.
Useful for experimental features not yet officially supported or other model's custom param called by openai client.
zh(optional): 
#265
> feat(libs/acl/openai): support extra fields  (#265)

- components/model/ark/chatmodel.go
> fix: set message name field in ark chat model

- components/model/ark/chatmodel.go
- components/model/ark/go.mod
- components/model/ark/go.sum
- components/model/arkbot/chatmodel.go
- components/model/arkbot/go.mod
- components/model/arkbot/go.sum
> feat: ark support json schema

- components/model/ark/chatmodel.go
- components/model/ark/option.go
> feat: add thinking option of ark model

- components/model/arkbot/README.md
> fix: remove apikey

- components/tool/bingsearch/README.md
- components/tool/bingsearch/README_zh.md
- components/tool/bingsearch/bing_search.go
- components/tool/bingsearch/bing_search_test.go
- components/tool/bingsearch/go.mod
- components/tool/duckduckgo/README.md
- components/tool/duckduckgo/README_zh.md
- components/tool/duckduckgo/search.go
- components/tool/duckduckgo/search_test.go
- components/tool/httprequest/README.md
- components/tool/httprequest/delete/delete.go
- components/tool/httprequest/delete/delete_test.go
- components/tool/httprequest/get/get.go
- components/tool/httprequest/get/get_test.go
- components/tool/httprequest/go.mod
- components/tool/httprequest/go.sum
- components/tool/httprequest/post/post.go
- components/tool/httprequest/post/post_test.go
- components/tool/httprequest/put/put.go
- components/tool/httprequest/put/put_test.go
- components/tool/wikipedia/README.md
- components/tool/wikipedia/README_zh.md
- components/tool/wikipedia/wikipedia.go
- components/tool/wikipedia/wikipedia_test.go
fix
en:
zh(optional): 
the jsonschema description of BingSearch, HTTPRequest, Wikipedia, Duckduckgo tools
> fix(tool): tool jsonschema description

- components/model/qwen/chatmodel.go
qwen thinking model param err ,  using chat_template_kwargs params to close thinking content
> fix(qwen): fix qwen enable thinking param

- libs/acl/openai/chat_model.go
> fix(acl_openai): support azure model mapper func

- components/model/ark/chatmodel.go
- components/model/ark/go.mod
- components/model/ark/go.sum
- components/model/ark/message_extra.go
> feat(ark): upgrade ark and support video

- components/model/gemini/gemini.go
> fix: gemini tool

- components/model/gemini/gemini.go
- components/model/gemini/gemini_test.go
> fix(gemini): multimodel content

- components/tool/duckduckgo/README.md
- components/tool/duckduckgo/README_zh.md
- components/tool/duckduckgo/search.go
> feat(tool_duckduckgo): deprecated v1

- components/prompt/mcp/go.mod
- components/prompt/mcp/go.sum
- components/tool/mcp/go.mod
- components/tool/mcp/go.sum
> feat: upgrade mcp version

- components/model/claude/claude.go
- components/model/claude/option.go
> feat(claude): support disable parallel tool use

- components/document/loader/file/file_loader.go
- components/document/loader/file/go.mod
- components/document/loader/file/go.sum
- components/document/loader/s3/go.mod
- components/document/loader/s3/go.sum
- components/document/loader/s3/s3_loader.go
- components/document/loader/url/go.mod
- components/document/loader/url/go.sum
- components/document/loader/url/url.go
> feat: support loader common options

- components/model/openai/chatmodel_test.go
- components/model/openai/go.mod
- components/model/openai/go.sum
- libs/acl/openai/chat_model.go
- libs/acl/openai/chat_model_test.go
- libs/acl/openai/go.mod
- libs/acl/openai/go.sum
- libs/acl/openai/option.go
> feat(acl_openai): add WithRequestBodySetter and WithExtraHeader model option

- components/model/ark/responses_api.go
> feat(model_ark): skip setting tools when contextID has been set

- components/embedding/ark/embedding.go
- components/embedding/ark/embedding_test.go
- components/embedding/ark/go.mod
- components/embedding/ark/go.sum
- components/model/ark/chatmodel.go
feat
en:
- support call ark multi-modal embedding model through EmbedStrings
zh(optional): 
- 支持通过 EmbedStrings 调用 ark 多模态向量化模型
> feat: support ark multi-modal text embedding

- callbacks/cozeloop/convert.go
- callbacks/cozeloop/convert_test.go
- callbacks/cozeloop/data_parser.go
- callbacks/cozeloop/data_parser_test.go
- callbacks/cozeloop/go.mod
- callbacks/cozeloop/go.sum
1. cozeloop callback model resp support finish_reason
2. update tool node span_type
> cozeloop callback model resp finish_reason

- libs/acl/openai/chat_model.go
> fix(acl_openai): Generate support promptTokenDetails

- components/model/ark/responses_api.go
- components/model/ark/responses_api_test.go
> fix(model_ark): callbackInput miss tool info

- callbacks/cozeloop/data_parser.go
- components/model/ark/responses_api.go
- components/model/ark/responses_api_test.go
- components/model/deepseek/deepseek.go
- components/model/gemini/gemini.go
fix
en:
1. [deepseek, gemini, ark] Miss CacheTokens in CallbackOutput.
2. [ark] Remove the system role to developer role conversion.
> fix(model): miss CachedTokens in CallbackOutput

- components/model/ark/responses_api.go
> fix(ark): ResponsesAPI stream finish_reason

- components/model/ark/chat_completion_api.go
- components/model/ark/chatmodel.go
- components/model/ark/responses_api.go
> feat(ark): support service iter

- libs/acl/openai/chat_model.go
fix
en:
zh(optional): 
Fixes #452
> fix(acl_openai): ResponseFormat JSONSchema

- a2a/extension/eino/client.go
- a2a/extension/eino/examples/client/client.go
> feat: modify eino agent config, from Transport to A2AClient

- callbacks/langfuse/langfuse.go
> Fix(langfuse): langfuse callback panic issue
